# Generated by Django 5.1.6 on 2025-03-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_userincome',
            name='incometype',
        ),
        migrations.RemoveField(
            model_name='tbl_userincome',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_userexpense',
        ),
        migrations.DeleteModel(
            name='tbl_userincome',
        ),
    ]
