# Generated by Django 5.1.6 on 2025-03-02 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0002_tbl_adminregistration_tbl_expensetype'),
        ('Guest', '0001_initial'),
        ('User', '0002_remove_tbl_userincome_incometype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_userexpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_expensefile', models.CharField(max_length=30)),
                ('user_expenseamount', models.CharField(max_length=30)),
                ('user_expensedate', models.DateField(auto_now_add=True)),
                ('expensetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_expensetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_userincome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_incomeamount', models.CharField(max_length=30)),
                ('user_incomedate', models.DateField(auto_now_add=True)),
                ('incometype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_incometype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
