# Generated by Django 5.1.6 on 2025-03-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_userexpense',
        ),
    ]
