# Generated by Django 5.1.6 on 2025-03-04 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_tbl_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='complaint_date',
        ),
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='complaint_reply',
        ),
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='complaint_status',
        ),
    ]
