# Generated by Django 5.1.6 on 2025-03-05 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_remove_tbl_complaint_complaint_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
