# Generated by Django 5.1.6 on 2025-03-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_tbl_savinghead'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_savinghead',
        ),
    ]
