# Generated by Django 5.1.6 on 2025-03-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_remove_tbl_savinghead_savinghead_id_tbl_savingbody_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_savingbody',
        ),
    ]
