# Generated by Django 5.1.6 on 2025-03-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_tbl_budget_tbl_savingbody'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_savingbody',
        ),
    ]
