# Generated by Django 5.1.6 on 2025-03-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_tbl_savingbody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_budget',
            name='expensecategory_id',
        ),
        migrations.RemoveField(
            model_name='tbl_budget',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.RemoveField(
            model_name='tbl_savingbody',
            name='savinghead_id',
        ),
        migrations.RemoveField(
            model_name='tbl_savinghead',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_budget',
        ),
        migrations.DeleteModel(
            name='tbl_savingbody',
        ),
        migrations.DeleteModel(
            name='tbl_savinghead',
        ),
    ]
