# Generated by Django 5.1.6 on 2025-03-08 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_adminregistration_tbl_expensetype'),
        ('Guest', '0001_initial'),
        ('User', '0023_remove_tbl_budget_expensecategory_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amount', models.CharField(max_length=100)),
                ('expensecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_expensetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=100)),
                ('complaint_content', models.TextField(max_length=100)),
                ('complaint_reply', models.TextField(max_length=100)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_status', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_savinghead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savinghead_title', models.CharField(max_length=30)),
                ('savinghead_goal', models.TextField(max_length=100)),
                ('savinghead_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_savingbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savingbody_amount', models.CharField(max_length=30)),
                ('savingbody_date', models.DateField(auto_now_add=True)),
                ('savinghead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_savinghead')),
            ],
        ),
    ]
