# Generated by Django 5.1.6 on 2025-03-08 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('User', '0028_delete_tbl_repayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_amount', models.CharField(max_length=30)),
                ('repayment_date', models.DateField(auto_now_add=True)),
                ('repayment_tenure', models.FileField(upload_to='TenureBill/')),
                ('repayment_name', models.TextField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
