# Generated by Django 5.1.6 on 2025-03-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0029_tbl_repayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_expense',
            name='expense_bill',
            field=models.FileField(upload_to='Assets/ExpenseBill/'),
        ),
        migrations.AlterField(
            model_name='tbl_repayment',
            name='repayment_tenure',
            field=models.FileField(upload_to='Assets/TenureBill/'),
        ),
        migrations.AlterField(
            model_name='tbl_userexpense',
            name='user_expensefile',
            field=models.FileField(upload_to='Assets/UserBill/'),
        ),
    ]
