# Generated by Django 5.1.6 on 2025-03-13 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('User', '0030_alter_tbl_expense_expense_bill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_id', models.CharField(max_length=30)),
                ('score_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
