# Generated by Django 5.1.6 on 2025-03-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_tbl_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_budget',
        ),
    ]
