# Generated by Django 5.1.6 on 2025-03-13 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_adminregistration_tbl_expensetype'),
        ('Guest', '0001_initial'),
        ('User', '0032_delete_tbl_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amount', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('expensecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_expensetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
