# Generated by Django 5.1.6 on 2025-03-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0035_tbl_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='complaint_reply',
        ),
    ]
