# Generated by Django 5.1.6 on 2025-03-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0036_remove_tbl_complaint_complaint_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
