# Generated by Django 5.1.7 on 2025-03-27 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('User', '0039_alter_tbl_budget_budget_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_repaymentnotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repaymentnotification_title', models.TextField(max_length=30)),
                ('repaymentnotification_description', models.TextField(max_length=100)),
                ('repaymentnotification_amount', models.TextField(max_length=30)),
                ('repaymentnotification_notificationdate', models.TextField(max_length=30)),
                ('repaymentnotification_paymentdate', models.TextField(max_length=30)),
                ('repaymentnotification_status', models.TextField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
