# Generated by Django 5.1.7 on 2025-03-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0040_tbl_repaymentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_repaymentnotification',
            name='last_acknowledged_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
