# Generated by Django 5.1.7 on 2025-04-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0041_tbl_repaymentnotification_last_acknowledged_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
