# Generated by Django 5.1.7 on 2025-04-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0043_tbl_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_repaymentnotification',
            name='repaymentnotification_notificationdate',
            field=models.IntegerField(),
        ),
    ]
