# Generated by Django 5.1.6 on 2025-04-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0045_alter_tbl_budget_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_savingbody',
            name='savingbody_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
