# Generated by Django 5.1.6 on 2025-04-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0046_alter_tbl_savingbody_savingbody_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_savingbody',
            name='savingbody_date',
            field=models.DateField(),
        ),
    ]
