# Generated by Django 5.1.7 on 2025-04-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0047_alter_tbl_savingbody_savingbody_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_budget',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbl_expense',
            name='expense_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_expense',
            name='expense_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbl_expense',
            name='expense_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbl_feedback',
            name='feedback_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbl_income',
            name='income_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbl_repayment',
            name='repayment_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbl_savingbody',
            name='savingbody_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbl_savinghead',
            name='savinghead_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
