# Generated by Django 5.1.7 on 2025-04-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0048_alter_tbl_budget_date_added_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_expense',
        ),
    ]
