# Generated by Django 5.1.7 on 2025-04-03 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_adminregistration_tbl_expensetype'),
        ('Guest', '0001_initial'),
        ('User', '0049_delete_tbl_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_amount', models.IntegerField()),
                ('expense_date', models.DateField(auto_now_add=True)),
                ('expense_time', models.TimeField(auto_now_add=True)),
                ('expense_note', models.TextField(blank=True, max_length=30)),
                ('expense_bill', models.FileField(blank=True, null=True, upload_to='Assets/ExpenseBill/')),
                ('expensecategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_expensetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
