# Generated by Django 5.1.7 on 2025-04-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0050_tbl_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_expense',
        ),
    ]
