# Generated by Django 5.1.7 on 2025-04-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0052_tbl_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_expense',
            name='expense_note',
            field=models.TextField(max_length=30),
        ),
        migrations.DeleteModel(
            name='tbl_savingbody',
        ),
    ]
