# Generated by Django 5.1.7 on 2025-04-04 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('User', '0053_alter_tbl_expense_expense_note_delete_tbl_savingbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_savingbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savingbody_amount', models.FloatField()),
                ('savingbody_date', models.DateField(auto_now_add=True)),
                ('savinghead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_savinghead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
