# Generated by Django 5.1.7 on 2025-04-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0054_tbl_savingbody'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_savingbody',
        ),
    ]
