# Generated by Django 5.1.7 on 2025-04-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0056_tbl_savingbody'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_score',
        ),
    ]
